---
    action-dim: 2
    cost:
      type: quadratic
      w:
        - 1
        - 2
        - 0.5
        - 0.75
    dt: 0.1
    env: ../envs/point_mass.xml
    goal:
      - 1
      - 2
      - 3
      - 4
    horizon: 12
    init-act:
      - 0.1
      - 0.2
    lambda: 1.5
    max-a:
      - 1.2
      - 1.3
    noise:
      - 0.24
      - 0.26
    samples: 3
    state-dim: 4
